language: node_js

node_js: 
  - "stable"

cache:
  directories:
    - "node_modules"

services: 
  - postgresql 

postgres: 
  adapter: postgresql
  database: mocha_chai_tv_shows_test
  username: postgres

before_script:
  - psql -c 'create database mocha_chai_tv_shows_test;' -U postgres
  - npm run db:setup

script:
  - npm test

after_success:
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  